# Generated by Django 4.1 on 2024-03-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pNome', models.CharField(max_length=100)),
                ('pData', models.DateField()),
                ('pSexo', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('pCpf', models.CharField(max_length=14, unique=True)),
                ('pAltura', models.FloatField()),
                ('pPeso', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
